version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/OnlineRetail.csv:/input_data/OnlineRetail.csv
      - postgres-db-volume-beg_de_proj:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres-db-volume-beg_de_proj:
