version: '3'

services:
  postgres-proj:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: qweasdzxc
      POSTGRES_DB: postgres
    volumes:
      - ./data:/data
      - postgres-db-volume-beg_de_proj:/var/lib/postgresql/data
    networks:
      - airflow-base_default
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres-db-volume-beg_de_proj:

networks:
  airflow-base_default:
      external: true
